# Generated by Django 2.0.5 on 2018-05-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20180512_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hour_salary',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.IntegerField(choices=[(1, 'Developer'), (2, 'Team Lead'), (3, 'Project Manager'), (4, 'CEO'), (5, 'CTO')], default=1),
        ),
    ]
