# Generated by Django 2.0.5 on 2018-05-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20180512_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overtimerequest',
            old_name='employer_id',
            new_name='employer',
        ),
    ]
