# Generated by Django 2.0.5 on 2018-05-13 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20180513_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workday',
            name='hours_worked',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
