# Generated by Django 2.0.5 on 2018-05-14 13:09

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_workday_last_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=application.models.get_report_pdf_name),
        ),
    ]
