# Generated by Django 2.0.5 on 2018-05-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_report_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimerequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1),
        ),
    ]
